# Notes on our CI:
# - Tests located test configuration annotated modules nested in the module
#   being tested.
# - Nightly rust used for support of the box keyword. Syntax is nicer, and 
#   directly allocates to heap.
# - Compiler Release is commented out to reduce pipeline time before release 
#   intention. This will be allowed to run at a later point.
image: rustlang/rust:nightly

stages:
  - build
  - test
  - lint
  - doc

build:
  stage: build
  script:
    - echo "Building the compiler..."
    - cargo build --verbose

test:
  stage: test
  script:
    - echo "Testing the compiler..."
    - cargo test --verbose -- --skip tests::examples_test

test-master:
  stage: test
  script:
    - echo "Testing the compiler..."
    - apt-get update && apt-get -y install qemu-user-static gcc-arm-linux-gnueabi
    - cargo test --verbose
  only:
    - master

formatter:
  stage: lint
  script:
    - echo "Fmt checking codebase..."
    - cargo fmt -- --check

linter:
  stage: lint
  script:
    - echo "Clippy checking codebase..."
    - cargo clippy -- -D warnings

pages:
  stage: doc
  script:
    - cargo doc
    - mkdir public
    - mv target/doc/* public
    - echo '<meta http-equiv="refresh" content="0; url=compile/index.html">' > public/index.html
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - master
