# Notes on our CI:
# - Tests located test configuration annotated modules nested in the module
#   being tested.
# - Nightly rust used for support of the box keyword. Syntax is nicer, and 
#   directly allocates to heap.
# - Compiler Release is commented out to reduce pipeline time before release 
#   intention. This will be allowed to run at a later point.
image: rustlang/rust:nightly

# invalid use of cache: cargo
# cache: cargo

stages:
  - build
  - test
  # - build-release

compiler-build:
  stage: build
  script:
    - echo "Building the compiler..."
    - cargo build --verbose

compiler-test:
  stage: test
  script:
    - echo "Testing the compiler..."
    - cargo test --verbose

linter:
  stage: test
  before_script:
  - rustup component add clippy
  script:
  # build job fails if there are warnings
  - cargo clippy -- -D warnings

formatter:
  before_script:
  - rustup component add rustfmt
  script:
  # build job fails if code is not formatted correctly
  - cargo fmt -- --check

auditor:
  before_script:
    - cargo install cargo-audit
    - cargo generate-lockfile
  script:
    - cargo audit

# compiler-build-release:
#   stage: build-release
#   script:
#     - echo "Building release version of compiler..."
#     - cargo build --release --verbose
