[package]
name = "wacc_33"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "compile"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.0"
nom-supreme = "0.6.0"
clap = "3.0.5"